name: Update README with Submodule Commits

on:
  schedule:
    - cron: '0 0 * * *'  # 定时执行，可以根据需要调整

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Submodules
        run: |
          git submodule update --init --recursive

      - name: Get Submodule Commits
        id: submodule_commits
        run: |
          submodule_path="path/to/submodule"  # 替换成实际的子模块路径
          cd "$submodule_path"
          commit_count=$(git rev-list --count HEAD)
          echo "::set-output name=commit_count::$commit_count"

      - name: Install GitPython
        run: pip install GitPython

      - name: Update README
        run: python os test.py
